### ISSUE TITLE
dydx start error

### ISSUE THREAD

**Issue by eson33** [dydxprotocol/v4-chain#1853]
root@7a72d55b2382:/go/src/v4/protocol/cmd/dydxprotocold# go run main.go start --home ./.dydxprotocol
3:10AM INF Parsed App flags Flags={"DdAgentHost":"","DdErrorTrackingFormat":false,"DdTraceAgentPort":8126,"GrpcAddress":"0.0.0.0:9090","GrpcEnable":true,"GrpcStreamingEnabled":false,"GrpcStreamingFlushIntervalMs":50,"GrpcStreamingMaxBatchSize":2000,"GrpcStreamingMaxChannelBufferSize":2000,"NonValidatingFullNode":false,"VEOracleEnabled":true} module=server
3:10AM INF Not initializing Datadog profiler. Application version was not defined during build time and no override has been provided by environment variable DD_VERSION. module=server
3:10AM INF Parsed Indexer flags Flags={"KafkaAddrs":[],"MaxRetries":3,"SendOffchainData":true} module=server
3:10AM INF Parsed Daemon flags Flags={"Bridge":{"Enabled":true,"EthRpcEndpoint":"","LoopDelayMs":30000},"Liquidation":{"Enabled":true,"LoopDelayMs":1600,"QueryPageLimit":1000},"Price":{"Enabled":false,"LoopDelayMs":3000},"Shared":{"MaxDaemonUnhealthySeconds":300,"PanicOnDaemonFailureEnabled":true,"SocketAddress":"/tmp/daemons.sock"},"Slinky":{"ClientTimeout":2000000000,"Enabled":true,"MetricsEnabled":false,"OracleAddress":"localhost:8080","PrometheusServerAddress":""}} module=server
3:10AM INF Parsed CLOB flags Flags={"MaxDeleveragingAttemptsPerBlock":10,"MaxDeleveragingSubaccountsToIterate":500,"MaxLiquidationAttemptsPerBlock":50,"MevTelemetryEnabled":false,"MevTelemetryHosts":[],"MevTelemetryIdentifier":""} module=server
3:10AM INF App instantiated app_version= git_commit= module=server
3:10AM INF starting node with ABCI CometBFT in-process module=server
3:10AM INF service start impl=multiAppConn module=proxy msg="Starting multiAppConn service"
3:10AM INF service start connection=query impl=unsyncLocalClient module=abci-client msg="Starting unsyncLocalClient service"
3:10AM INF service start connection=snapshot impl=unsyncLocalClient module=abci-client msg="Starting unsyncLocalClient service"
3:10AM INF service start connection=mempool impl=unsyncLocalClient module=abci-client msg="Starting unsyncLocalClient service"
3:10AM INF service start connection=consensus impl=unsyncLocalClient module=abci-client msg="Starting unsyncLocalClient service"
3:10AM INF service start impl=EventBus module=events msg="Starting EventBus service"
3:10AM INF service start impl=PubSub module=pubsub msg="Starting PubSub service"
3:10AM INF service start impl=IndexerService module=txindex msg="Starting IndexerService service"
3:10AM INF ABCI Handshake App Info hash=E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855 height=0 module=consensus protocol-version=0 software-version=
3:10AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
3:10AM INF InitChain chainID=my-test-chain initialHeight=1 module=server
ssssssssssssssss 111 1000000000000000000
3:10AM INF initializing blockchain state from genesis.json module=server
3:10AM INF Created new epoch info (current block time = 1720148683): {Name:funding-sample NextTick:30 Duration:60 CurrentEpoch:0 CurrentEpochStartBlock:0 IsInitialized:false FastForwardNextTick:true} module=server
3:10AM INF Created new epoch info (current block time = 1720148683): {Name:funding-tick NextTick:0 Duration:3600 CurrentEpoch:0 CurrentEpochStartBlock:0 IsInitialized:false FastForwardNextTick:true} module=server
3:10AM INF Created new epoch info (current block time = 1720148683): {Name:stats-epoch NextTick:0 Duration:3600 CurrentEpoch:0 CurrentEpochStartBlock:0 IsInitialized:false FastForwardNextTick:true} module=server
3:10AM INF asserting crisis invariants inv=1/12 module=x/crisis name=bank/nonnegative-outstanding
3:10AM INF asserting crisis invariants inv=2/12 module=x/crisis name=bank/total-supply
3:10AM INF asserting crisis invariants inv=3/12 module=x/crisis name=gov/module-account
3:10AM INF asserting crisis invariants inv=4/12 module=x/crisis name=distribution/nonnegative-outstanding
3:10AM INF asserting crisis invariants inv=5/12 module=x/crisis name=distribution/can-withdraw
3:10AM INF asserting crisis invariants inv=6/12 module=x/crisis name=distribution/reference-count
3:10AM INF asserting crisis invariants inv=7/12 module=x/crisis name=distribution/module-account
3:10AM INF asserting crisis invariants inv=8/12 module=x/crisis name=transfer/total-escrow-per-denom
3:10AM INF asserting crisis invariants inv=9/12 module=x/crisis name=staking/module-accounts
3:10AM INF asserting crisis invariants inv=10/12 module=x/crisis name=staking/nonnegative-power
3:10AM INF asserting crisis invariants inv=11/12 module=x/crisis name=staking/positive-delegation
3:10AM INF asserting crisis invariants inv=12/12 module=x/crisis name=staking/delegator-shares
3:10AM INF asserted all invariants duration=3.0462 height=0 module=x/crisis
3:10AM INF created new capability module=ibc name=ports/transfer
3:10AM INF port binded module=x/ibc/port port=transfer
3:10AM INF claimed capability capability=1 module=transfer name=ports/transfer
3:10AM INF created new capability module=ibc name=ports/icahost
3:10AM INF port binded module=x/ibc/port port=icahost
3:10AM INF claimed capability capability=2 module=icahost name=ports/icahost
3:10AM INF Closing application.db module=server
3:10AM INF Closing snapshots/metadata.db module=server
panic: validator set is empty after InitGenesis, please ensure at least one validator is initialized with a delegation greater than or equal to the DefaultPowerReduction ({824640800160})

goroutine 1 [running]:
github.com/dydxprotocol/v4-chain/protocol/app.(*App).InitChainer(_, {{0x5964fa8, 0x7b76b20}, {0x59863c0, 0xc002a38740}, {{0x0, 0x0}, {0xc005d48200, 0xd}, 0x0, ...}, ...}, ...)
        /go/src/v4/protocol/app/app.go:1709 +0x425
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc005e5a508, 0xc000677500)
        /go/pkg/mod/github.com/dydxprotocol/cosmos-sdk@v0.50.6-0.20240606183841-18966898625f/baseapp/abci.go:108 +0x702
github.com/cosmos/cosmos-sdk/server.cometABCIWrapper.InitChain(...)
        /go/pkg/mod/github.com/dydxprotocol/cosmos-sdk@v0.50.6-0.20240606183841-18966898625f/server/cmt_abci.go:32

**Comment by eson33** [comment]
> [GH-45 dydx 启动错误](https://linear.app/dydx/issue/GH-45/dydx-start-error)

![image](https://github.com/dydxprotocol/v4-chain/assets/173236453/aebc51f0-6895-4740-91ae-9d30ba02611f)
