### ISSUE TITLE
Indexer: local deployment error in ender container "Error: Failed to parse private key: Error: Invalid PEM formatted message."

### ISSUE THREAD

**Issue by sl4mmy** [dydxprotocol/v4-chain#2565]
Following the instructions for deploying locally (https://github.com/dydxprotocol/v4-chain/tree/main/indexer#deploying) in a fresh clone at tag `indexer/v7.0.1`:

```
...
ender-1             | 2024-11-08 16:07:23 [error]: {
ender-1             |   "at": "notifications#firebase",
ender-1             |   "message": "Failed to initialize Firebase App",
ender-1             |   "error": {
ender-1             |     "message": "Failed to parse private key: Error: Invalid PEM formatted message.",
ender-1             |     "errorInfo": {
ender-1             |       "code": "app/invalid-credential",
ender-1             |       "message": "Failed to parse private key: Error: Invalid PEM formatted message."
ender-1             |     },
ender-1             |     "codePrefix": "app"
ender-1             |   },
ender-1             |   "timestamp": "2024-11-08T16:07:23.883Z"
ender-1             | }
ender-1             | 2024-11-08 16:07:23 [info]: {
ender-1             |   "at": "index#start",
ender-1             |   "message": "Connecting to redis: redis://redis:6379",
ender-1             |   "timestamp": "2024-11-08T16:07:23.901Z"
ender-1             | }
ender-1             | 2024-11-08 16:07:23 [info]: {
ender-1             |   "at": "index#start",
ender-1             |   "message": "Connecting to kafka brokers: kafka:9092",
ender-1             |   "timestamp": "2024-11-08T16:07:23.901Z"
ender-1             | }
ender-1             | 2024-11-08 16:07:23 [info]: {
ender-1             |   "at": "index#start",
ender-1             |   "message": "Starting in env development",
ender-1             |   "timestamp": "2024-11-08T16:07:23.902Z"
ender-1             | }
ender-1             | Error: Failed to parse private key: Error: Invalid PEM formatted message.
ender-1             |     at new ServiceAccount (/home/dydx/app/node_modules/.pnpm/firebase-admin@12.4.0/node_modules/firebase-admin/lib/app/credential-internal.js:153:19)
ender-1             |     at new ServiceAccountCredential (/home/dydx/app/node_modules/.pnpm/firebase-admin@12.4.0/node_modules/firebase-admin/lib/app/credential-internal.js:70:15)
ender-1             |     at cert (/home/dydx/app/node_modules/.pnpm/firebase-admin@12.4.0/node_modules/firebase-admin/lib/app/credential-factory.js:103:54)
ender-1             |     at initializeFirebaseApp (/home/dydx/app/packages/notifications/build/src/lib/firebase.js:29:40)
ender-1             |     at Object.<anonymous> (/home/dydx/app/packages/notifications/build/src/lib/firebase.js:46:21)
ender-1             |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
ender-1             |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
ender-1             |     at Module.load (node:internal/modules/cjs/loader:981:32)
ender-1             |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ender-1             |     at Module.require (node:internal/modules/cjs/loader:1005:19)
ender-1             |     at Module.Hook.Module.require (/home/dydx/app/node_modules/.pnpm/dd-trace@3.32.1/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
ender-1             |     at require (node:internal/modules/cjs/helpers:102:18)
ender-1             |     at Object.<anonymous> (/home/dydx/app/packages/notifications/build/src/index.js:17:14)
ender-1             |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
ender-1             |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
ender-1             |     at Module.load (node:internal/modules/cjs/loader:981:32)
ender-1             | 2024-11-08 16:07:23 [info]: {
ender-1             |   "at": "redis#ready",
ender-1             |   "message": "Connected to redis. Started to load scripts.",
ender-1             |   "timestamp": "2024-11-08T16:07:23.984Z"
ender-1             | }
```

**Comment by fl4p** [comment]
Same here
